apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend # connecting Deployment and Pod (Deployment will manage Pods which have this label)
  template:
    metadata:
      labels:
        app: backend # set label on Pod
      annotations:
        co.elastic.log/enabled: "true"
        co.elastic.log/module: springboot
        co.elastic.logs/json.keys_uder_root: "true"
        co.elastic.logs/json.add_error_key: "true"
    spec:
      containers:
        - name: backend
          image: nobugsme/nbank:with_username_error_fix
          imagePullPolicy: Always
          ports:
            - containerPort: 4111
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend # Service will rout traffic to Pods which label "app" = "backend"
  ports:
    - name: http
      protocol: TCP
      port: 4111 # port where service works
      targetPort: 4111 # port where forward inside Pod (container listens to this port)
  type: NodePort #ClusterIP (available inside cluster), NodePort opens port on all Nodes of cluster

# SCHEMA:
# [you browser or test] - http://<NODE-IP>:4111 (or http://localhost:4111)
# |
# [NodePort 4111]
# |
# [Service port 4111]
# |
# [Pod / Container port 4111]
# |
# image: nobugsme/nbank:with_username_error_fix
