apiBaseUrl=http://localhost:4111
apiVersion=/api/v1
testsVersion=with_database

admin.username=admin
admin.password=admin

uiRemote=http://localhost:4444/wd/hub
# for local run without docker-compose.yml execution
-uiBaseUrl=http://localhost:3000
# for run with docker-compose.yml execution
uiBaseUrl=http://frontend
browser=chrome
browserSize=1920x1080

# Database configuration
db.url=jdbc:postgresql://localhost:5433/nbank
db.username=postgres
db.password=postgres
db.driver=org.postgresql.Driver
db.table.customers=customers